### ISSUE TITLE
Error when exiting blender

### ISSUE THREAD

**Issue by ideasman42** [johnnygizmo/BulkAsset#3]
Exiting raises an error with blender `05617ed07d2bc33102e3f47fd0c11395e56b3972`.

The exception is:

```
Traceback (most recent call last):                                                                                                             
  File "/src/cmake_debug/bin/4.2/scripts/modules/addon_utils.py", line 511, in disable                                                         
    mod.unregister()                                                                                                                           
  File "/home/ideasman42/.config/blender/4.2/extensions/blender_org/bulk_asset_tools/__init__.py", line 80, in unregister                      
    bpy.types.ASSETBROWSER_MT_asset.remove(header_menu_func)                                                                                   
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                            
AttributeError: 'module' object has no attribute 'ASSETBROWSER_MT_asset'        
```

**Comment by johnnygizmo** [comment]
This should be fixed in master now. Also published to https://extensions.blender.org/
