### ISSUE TITLE
Asset Mover - empty

### ISSUE THREAD

**Issue by PeterP1975** [johnnygizmo/BulkAsset#6]
Empty Asset Mover list probably due to Blender portable installation

**Comment by HamousOnWheels** [comment]
i am facing this same issue in blender 4.5 and 5.2 (normal non portable installation). looking at the console it seems it's bothered by emoji in the path: 

```
FileNotFoundError: [Errno 2] No such file or directory: 'Y:\\\\Libraries\\\\3D Objects\\\\\\xf0\\x9f\\xa7\\x8a blender assets\\\\online essentials\\\\blender_assets.cats.txt'
File "C:\Users\username\AppData\Roaming\Blender Foundation\Blender\4.5\extensions\blender_org\bulk_asset_tools\utilities.py", line 27, in item_callback
Traceback (most recent call last):
  File "C:\Users\username\AppData\Roaming\Blender Foundation\Blender\4.5\extensions\blender_org\bulk_asset_tools\utilities.py", line 38, in item_callback
    cat = open(os.path.join(str(directory), "blender_assets.cats.txt"))
```

the actual path is `Y:\Libraries\3D Objects\🧊 blender assets\online essentials\`. the issue does not appear in libraries without emoji in the path
